CI: Downgrade to Ubuntu 18.04 to avoid get-pip
There have been a recent update to the `get-pip.py` script for
installing `pip` for python 2.7. This updated causes installing pip to
fail with the following error message:
```
Traceback (most recent call last):
  File "get-pip.py", line 24226, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmpG8aJb5/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

This commit downgrades the Ubuntu version from 20.04 to 18.04 to avoid
using this script. Ubuntu 18.04 can install pip from the default repo,
avoiding `get-pip.py` entirely.

Another benefit is that it simplifies the setup script as well.